services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:cuda
    restart: unless-stopped
    ports:
      - "8080:8080"
    runtime: nvidia  # Ensures GPU access
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/daniel/Storage/Dev/OpenWebUIData/:/app/backend/data
    networks:
      - agent_swarm
    env_file:
      - /home/daniel/Storage/Dev/OpenWebUIData/secrets.env 

  hive_mind:
    container_name: hive_mind
    build: .
    working_dir: /usr/src/app
    ports:
      - "7977:7977"
    env_file:
      - secrets.env
    restart: unless-stopped
    networks:
      - agent_swarm
    volumes:
      - /home/daniel/Storage/Dev/hive_mind/agents/:/usr/src/app/agents

networks:
  agent_swarm: