services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:cuda
    restart: unless-stopped
    ports:
      - "8080:8080"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /home/daniel/Storage/Dev/OpenWebUIData/:/app/backend/data
    networks:
      - agent_swarm
    env_file:
      - /home/daniel/Storage/Dev/OpenWebUIData/secrets.env 

  # gradio_server:
  #   build: .
  #   container_name: gradio_server
  #   working_dir: /usr/src/app
  #   command: ./venv/bin/python gradio_app.py
  #   ports:
  #     - "7977:7977"
  #   volumes:
  #     - /home/daniel/Storage/Dev/hive_mind:/usr/src/app/hive_mind
  #   env_file:
  #     - .env
  #   networks:
  #     - agent_swarm
  #   restart: unless-stopped

  # fastapi_server:
  #   build: .
  #   container_name: fastapi_server
  #   working_dir: /usr/src/app
  #   command: ./venv/bin/uvicorn fastapi_server:app --host 0.0.0.0 --port 7779 --reload
  #   ports:
  #     - "7779:7779"
  #   volumes:
  #     - /home/daniel/Storage/Dev/hive_mind:/usr/src/app/hive_mind
  #   env_file:
  #     - .env
  #   networks:
  #     - agent_swarm
  #   restart: unless-stopped

  # mcp_server:
  #   build: .
  #   container_name: mcp_server
  #   working_dir: /usr/src/app
  #   command: ./venv/bin/mcpo --port 7777 -- ./venv/bin/python mcp_server.py
  #   ports:
  #     - "7777:7777"
  #   volumes:
  #     - /home/daniel/Storage/Dev/hive_mind:/usr/src/app/hive_mind
  #   env_file:
  #     - .env
  #   networks:
  #     - agent_swarm
  #   restart: unless-stopped

networks:
  agent_swarm:
